
package it.csi.iscritto.iscrittofosrv.integration.service.nao.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JavaServiceDescService", targetNamespace = "urn:SrvVisuraFamiglia", wsdlLocation = "http://mfsvil2.csi.it:8405/wsfad_naosrv_wsicompliant/services/SrvVisuraFamiglia?wsdl")
public class JavaServiceDescService
    extends Service
{

    private final static URL JAVASERVICEDESCSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAVASERVICEDESCSERVICE_EXCEPTION;
    private final static QName JAVASERVICEDESCSERVICE_QNAME = new QName("urn:SrvVisuraFamiglia", "JavaServiceDescService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mfsvil2.csi.it:8405/wsfad_naosrv_wsicompliant/services/SrvVisuraFamiglia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAVASERVICEDESCSERVICE_WSDL_LOCATION = url;
        JAVASERVICEDESCSERVICE_EXCEPTION = e;
    }

    public JavaServiceDescService() {
        super(__getWsdlLocation(), JAVASERVICEDESCSERVICE_QNAME);
    }

    public JavaServiceDescService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns JavaServiceDesc
     */
    @WebEndpoint(name = "SrvVisuraFamiglia")
    public JavaServiceDesc getSrvVisuraFamiglia() {
        return super.getPort(new QName("urn:SrvVisuraFamiglia", "SrvVisuraFamiglia"), JavaServiceDesc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JavaServiceDesc
     */
    @WebEndpoint(name = "SrvVisuraFamiglia")
    public JavaServiceDesc getSrvVisuraFamiglia(WebServiceFeature... features) {
        return super.getPort(new QName("urn:SrvVisuraFamiglia", "SrvVisuraFamiglia"), JavaServiceDesc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAVASERVICEDESCSERVICE_EXCEPTION!= null) {
            throw JAVASERVICEDESCSERVICE_EXCEPTION;
        }
        return JAVASERVICEDESCSERVICE_WSDL_LOCATION;
    }

}
