
package it.csi.iscritto.iscrittofosrv.integration.service.nao.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JavaServiceDesc", targetNamespace = "urn:SrvVisuraFamiglia")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JavaServiceDesc {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.Vector
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws TooManyItemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "testataFamigliePerIDReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "testataFamigliePerID", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.TestataFamigliePerID")
    @ResponseWrapper(localName = "testataFamigliePerIDResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.TestataFamigliePerIDResponse")
    public Vector testataFamigliePerID(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        List<Integer> in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, TooManyItemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerIDReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerID", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerID")
    @ResponseWrapper(localName = "dettaglioFamigliaPerIDResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerIDResponse")
    public DettaglioFamiglia dettaglioFamigliaPerID(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        int in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerNumeroFamigliaReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerNumeroFamiglia", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerNumeroFamiglia")
    @ResponseWrapper(localName = "dettaglioFamigliaPerNumeroFamigliaResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerNumeroFamigliaResponse")
    public DettaglioFamiglia dettaglioFamigliaPerNumeroFamiglia(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerIdSoggettoReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerIdSoggetto", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerIdSoggetto")
    @ResponseWrapper(localName = "dettaglioFamigliaPerIdSoggettoResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerIdSoggettoResponse")
    public DettaglioFamiglia dettaglioFamigliaPerIdSoggetto(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        int in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerNumeroIndividualeReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerNumeroIndividuale", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerNumeroIndividuale")
    @ResponseWrapper(localName = "dettaglioFamigliaPerNumeroIndividualeResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerNumeroIndividualeResponse")
    public DettaglioFamiglia dettaglioFamigliaPerNumeroIndividuale(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerCartaIdentitaReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerCartaIdentita", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerCartaIdentita")
    @ResponseWrapper(localName = "dettaglioFamigliaPerCartaIdentitaResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerCartaIdentitaResponse")
    public DettaglioFamiglia dettaglioFamigliaPerCartaIdentita(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamiglia
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioFamigliaPerCodiceFiscaleReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioFamigliaPerCodiceFiscale", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerCodiceFiscale")
    @ResponseWrapper(localName = "dettaglioFamigliaPerCodiceFiscaleResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaPerCodiceFiscaleResponse")
    public DettaglioFamiglia dettaglioFamigliaPerCodiceFiscale(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in2)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.Vector
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "visuraFamiglieInCoabitazioneReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "visuraFamiglieInCoabitazione", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamiglieInCoabitazione")
    @ResponseWrapper(localName = "visuraFamiglieInCoabitazioneResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamiglieInCoabitazioneResponse")
    public Vector visuraFamiglieInCoabitazione(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        int in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in2,
        @WebParam(name = "in3", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in3)
        throws FormalException_Exception, ServiceException_Exception, SystemException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaStorico
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "visuraFamigliaAllaDataPerIdSoggettoReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "visuraFamigliaAllaDataPerIdSoggetto", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerIdSoggetto")
    @ResponseWrapper(localName = "visuraFamigliaAllaDataPerIdSoggettoResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerIdSoggettoResponse")
    public DettaglioFamigliaStorico visuraFamigliaAllaDataPerIdSoggetto(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        int in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in2,
        @WebParam(name = "in3", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in3)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaStorico
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "visuraFamigliaAllaDataPerIdFamigliaReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "visuraFamigliaAllaDataPerIdFamiglia", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerIdFamiglia")
    @ResponseWrapper(localName = "visuraFamigliaAllaDataPerIdFamigliaResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerIdFamigliaResponse")
    public DettaglioFamigliaStorico visuraFamigliaAllaDataPerIdFamiglia(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        int in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in2,
        @WebParam(name = "in3", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in3)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioFamigliaStorico
     * @throws FamigliaNotFoundException_Exception
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "visuraFamigliaAllaDataPerNumeroFamigliaReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "visuraFamigliaAllaDataPerNumeroFamiglia", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerNumeroFamiglia")
    @ResponseWrapper(localName = "visuraFamigliaAllaDataPerNumeroFamigliaResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.VisuraFamigliaAllaDataPerNumeroFamigliaResponse")
    public DettaglioFamigliaStorico visuraFamigliaAllaDataPerNumeroFamiglia(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in2,
        @WebParam(name = "in3", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in3)
        throws FamigliaNotFoundException_Exception, FormalException_Exception, ServiceException_Exception, SystemException_Exception, UnauthorizedException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.util.List<it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioMinimoFamiglia>
     * @throws UnauthorizedException_Exception
     * @throws SystemException_Exception
     * @throws TooManyItemException_Exception
     * @throws ServiceException_Exception
     * @throws FormalException_Exception
     */
    @WebMethod
    @WebResult(name = "dettaglioMinimoFamigliePerIDReturn", targetNamespace = "urn:SrvVisuraFamiglia")
    @RequestWrapper(localName = "dettaglioMinimoFamigliePerID", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioMinimoFamigliePerID")
    @ResponseWrapper(localName = "dettaglioMinimoFamigliePerIDResponse", targetNamespace = "urn:SrvVisuraFamiglia", className = "it.csi.iscritto.iscrittofosrv.integration.service.nao.client.DettaglioMinimoFamigliePerIDResponse")
    public List<DettaglioMinimoFamiglia> dettaglioMinimoFamigliePerID(
        @WebParam(name = "in0", targetNamespace = "urn:SrvVisuraFamiglia")
        List<Integer> in0,
        @WebParam(name = "in1", targetNamespace = "urn:SrvVisuraFamiglia")
        boolean in1,
        @WebParam(name = "in2", targetNamespace = "urn:SrvVisuraFamiglia")
        DatiProfilati in2,
        @WebParam(name = "in3", targetNamespace = "urn:SrvVisuraFamiglia")
        UtenteServizio in3)
        throws FormalException_Exception, ServiceException_Exception, SystemException_Exception, TooManyItemException_Exception, UnauthorizedException_Exception
    ;

}
